name: 'Inclusiveness Analyzer'
description: 'This GitHub action scans your repository for non-inclusive terms and provide alternative suggestions.'
inputs:
  failOnNonInclusiveTerm:
    description: 'Fails the step if a non-inclusive term is found'
    required: false
    default: 'false'
  excludeUnchangedFiles:
    description: 'Only scan files added or modified in last commit when checkout step has "with: fetch-depth: 2" configured'
    required: false
    default: 'true'
  excludeFiles:
    description: 'Comma separated list of file patterns to exclude from analysis'
    required: false
  excludeTerms:
    description: 'Comma separated list of non-inclusive terms to exclude from analysis'
    required: false
  maxLineLength:
    description: 'Maximum line length to scan'
    required: false
    default: '1000'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'heart'
  color: 'green'
