name: 'Inclusiveness Analyzer'
description: 'This GitHub action scans your repository for non-inclusive terms and provide alternative suggestions.'
inputs:
  failStep:
    description: 'Fails the step if a non-inclusive term is found'
    required: false
    default: 'false'
  excludeTerms:
    description: 'Comma separated list of non-inclusive terms to exclude from analysis'
    required: false
  excludeFromScan:
    description: 'Comma separated list of file patterns to exclude from analysis'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'heart'
  color: 'green'
